apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: github-copilot-report-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-copilot-report
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-copilot-report
  template:
    metadata:
      labels:
        app: github-copilot-report
    spec:
      containers:
      - name: github-copilot-report
        image: prima101112/github-copilot-report:latest
        ports:
        - containerPort: 8501
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
        env:
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: copilot-metrics-secret
              key: GITHUB_TOKEN
        - name: ORG_SLUG
          value: "your_organization_name"  # Replace with your GitHub organization name
        - name: DB_PATH
          value: "/app/data"  # Path to store database
        volumeMounts:
        - name: data-volume
          mountPath: /app/data  # Adjust this path to match where your app stores the SQLite database
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: github-copilot-report-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: github-copilot-report
spec:
  selector:
    app: github-copilot-report
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
  type: ClusterIP
